# Generated by Django 6.0.7 on 2026-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's mobile number.", max_length=20, null=True, unique=True),
        ),
    ]
